### ISSUE TITLE
Thanks for your solution

### ISSUE THREAD

**Issue by ghost** [y3km21/fresh_twind-v1_plugin#2]
Sorry it is not an Issue, but I feel I need to thank you and write here.
Thanks to your repository I can take full advantage of colors such as slate and other new features of Twind on my blog.
Biggest thanks. :)

**Comment by y3km21** [comment]
@kstdx  Thanks for your comments!
I'm glad this repository is useful to you.
Probably the next fresh will support twind v1.  denoland/fresh#946 denoland/fresh#1050
Please make sure you use that one when it is released.
